# Generated by Django 5.1.1 on 2024-09-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='max_length',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Deilvery'), ('ONLINE', 'Card Payment'), ('UPI', 'UPI Payment')], max_length=20, null=True),
        ),
    ]
