# Generated by Django 5.1.1 on 2024-09-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_max_length_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymet_status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20, null=True),
        ),
    ]
